### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by willbenica** [peri4n/vagrant-ldap#1]
The README has the following lines:
>You can query the EU server like:
>`ldapsearch -x -H ldap://localhost:3891 -b dc=eu,dc=company,dc=example -D cn=admin,dc=eu,dc=company,dc=example -w 1234`

After installing and running `vagrant up` and trying the above query, I noticed that we don't start a machine with port 3891. Trying the above leads to:
`ldap_result: Can't contact LDAP server (-1)`

As far as I see, we're only starting three servers with ports `3892` - `3894`.

README should reflect that.

**Comment by peri4n** [comment]
Clarified. The EU1 server started without provisioning...
